export const genreTranslations = {
    Action: "Acción",
    Adventure: "Aventura",
    "Avant Garde": "Avant Garde",
    "Award Winning": "Ganadores de premios",
    "Boys Love": "Amor entre chicos",
    Comedy: "Comedia",
    Drama: "Drama",
    Fantasy: "Fantasía",
    "Girls Love": "Amor entre chicas",
    Gourmet: "Gourmet",
    Horror: "Terror",
    Mystery: "Misterio",
    Romance: "Romance",
    "Sci-Fi": "Ciencia ficción",
    "Slice of Life": "Slice of Life",
    Sports: "Deportes",
    Supernatural: "Sobrenatural",
    Suspense: "Suspense",
    Ecchi: "Ecchi",
    Erotica: "Erótico",
    Hentai: "Hentai",
    "Adult Cast": "Reparto adulto",
    Anthropomorphic: "Antropomórfico",
    CGDCT: "CGDCT",
    Childcare: "Cuidado de niños",
    "Combat Sports": "Deportes de combate",
    Crossdressing: "Travestismo",
    Delinquents: "Delincuentes",
    Detective: "Detective",
    Educational: "Educativo",
    "Gag Humor": "Humor de gag",
    Gore: "Gore",
    Harem: "Harén",
    "High Stakes Game": "Juego de altas apuestas",
    Historical: "Histórico",
    "Idols (Female)": "Ídolos (Femenino)",
    "Idols (Male)": "Ídolos (Masculino)",
    Isekai: "Isekai",
    Iyashikei: "Iyashikei",
    "Love Polygon": "Polígono de amor",
    "Magical Sex Shift": "Cambio mágico de género",
    "Mahou Shoujo": "Mahou Shoujo",
    "Martial Arts": "Artes marciales",
    Mecha: "Mecha",
    Medical: "Médico",
    Military: "Militar",
    Music: "Música",
    Mythology: "Mitología",
    "Organized Crime": "Crimen organizado",
    "Otaku Culture": "Cultura otaku",
    Parody: "Parodia",
    "Performing Arts": "Artes escénicas",
    Pets: "Mascotas",
    Psychological: "Psicológico",
    Racing: "Carreras",
    Reincarnation: "Reencarnación",
    "Reverse Harem": "Harén inverso",
    "Romantic Subtext": "Subtexto romántico",
    Samurai: "Samurái",
    School: "Escuela",
    Showbiz: "Mundo del espectáculo",
    Space: "Espacio",
    "Strategy Game": "Juego de estrategia",
    "Super Power": "Superpoder",
    Survival: "Supervivencia",
    "Team Sports": "Deportes en equipo",
    "Time Travel": "Viaje en el tiempo",
    Vampire: "Vampiros",
    "Video Game": "Videojuego",
    "Visual Arts": "Artes visuales",
    Workplace: "Ambiente laboral",
    Josei: "Josei",
    Kids: "Niños",
    Seinen: "Seinen",
    Shoujo: "Shoujo",
    Shounen: "Shounen",
};

export const dayTranslations = {
    Mondays: 'Lunes',
    Tuesdays: 'Martes',
    Wednesdays: 'Miércoles',
    Thursdays: 'Jueves',
    Fridays: 'Viernes',
    Saturdays: 'Sábados',
    Sundays: 'Domingos',
};